[global]
	server min protocol = NT1
	server max protocol = NT1
	lanman auth = yes
	ntlm auth = yes
	map to guest = never
	log level = 1

[PS2SMB]
	path = /srv/ps2smb
	browseable = yes
	read only = no
	writable = yes
	guest ok = yes
	force user = matheus
