set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

set -g mouse on
set -g history-limit 10000
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind | split-window -h
bind - split-window -v

bind x kill-pane
bind K kill-server

set -g status-position bottom
set -g status-interval 5

set -g status-left-length 100
set -g status-right-length 100

run '~/.config/tmux/plugins/tpm/tpm'
