backend = "xrender";

vsync = false;

shadow = true;
shadow-radius = 7;

#fading = true;
#fading-in-step = 0.05;
#fading-out-step = 0.05;

inactive-opacity = 1.0;
active-opacity = 1.0;

#blur-background = true;
